### ISSUE TITLE
Don't lose precision when storing timestamps from the API

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton_rails#106]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1337, http://dev.mconf.org/redmine/issues/1337

---

Currently most of the times returned by BigBlueButton's API are in the format of a timestamp, a number with 13 digits.
Most of them are being converted to DateTime objects and stored in the database as datetime columns. Doing so we're losing millisecond precision.
In some cases these values might be necessary to pass as parameters in API calls, cases in which we might need the milliseconds to be included.

One way to store these numbers without losing precision is in a decimal column. A decimal(14,0) should be enough.
Moreover, the gem could include helpers to return this numbers as DateTimes. So the default would be to return an integer, but it would be easy to get it as a DateTime (e.g. @BigbluebuttonRecording#start_time@ returns and integer and @BigbluebuttonRecording#formatted_start_time@ returns a DateTime).

It can be done exactly like it was done for @BigbluebuttonRoom#create_time@ (https://github.com/mconf/bigbluebutton_rails/commit/091fe5759709bddf69181ce3c72e9bbc71dcab3d). Might also require some changes in @bigbluebutton-api-ruby@.

**Comment by daronco** [comment]
Implemented in the branch `v3-gem`, currently being tested with `mconf/mconf-web@v3`.

**Comment by daronco** [comment]
Fixed by #136 and will be further improved by #128.
