### ISSUE TITLE
Issue storing the size of recordings with more than 2 GB

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton_rails#116]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1793, http://dev.mconf.org/redmine/issues/1793

---

The column "size" in recordings is using the data type INT from MySQL. The maximum value for this data type is 4294967295, which corresponds to a recording of about 2.15 GB. This is not enough, recordings can certainly be bigger than this.

The column should use a data type that supports bigger values. 
Once possible type is BIGINT, that would support recordings up to ~ 9223372036.85 GB.

More at: http://dev.mysql.com/doc/refman/5.6/en/integer-types.html

**Comment by daronco** [comment]
This is implemented since v2.0.0 (see e7310a061fb61c7f179bb5d86f8716699ce5de7a).
