### ISSUE TITLE
How to create new servers?

### ISSUE THREAD

**Issue by pandugreycampus** [mconf/bigbluebutton_rails#31]
Hello,

I integrated the bigbluebutton into my rails app with following gem

gem 'bigbluebutton_rails', github: 'mconf/bigbluebutton_rails'

I get all routes and views but when i create a new server it giving me an error like below

PG::UndefinedTable: ERROR: relation "bigbluebutton_server_configs" does not exist LINE 5: WHERE a.attrelid = '"bigbluebutton_server_con... ^ : SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"bigbluebutton_server_configs"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum 

It may be with database tables. 
How can i solve this problem?

Help me!
![bbb](https://cloud.githubusercontent.com/assets/12657840/12580639/2cdf451a-c457-11e5-80be-106b34e918e6.png)

**Comment by daronco** [comment]
Are you using PostgreSQL? Are your migrations all running without errors?
There's a table named "bigbluebutton_server_configs" that apparently doesn't exist in your setup, but it should. Take a look at your migration files and see if they create this table. If you installed the gem correctly, it should be in a migration file that includes "bigbluebutton_rails" in its name.

It might be some specific of PostgreSQL, but it's hard to know since [we recommend MySQL](https://github.com/mconf/bigbluebutton_rails#database) instead.

**Comment by pandugreycampus** [comment]
I already checked in migration file but it does not contain any code to create a table "bigbluebutton_server_configs" and as well as migration are executed with out any errors.

**Comment by 4itosik** [comment]
@pandugreycampus, I have this error, when I use ` gem 'bigbluebutton_rails'`.

In bigbluebutton_rails migration I don't have `bigbluebutton_server_configs` table.

I remove all (rollback db too).

Add `gem 'bigbluebutton_rails', github: 'mconf/bigbluebutton_rails'` to Gemfile.
`bundle`
and when  I use `rails generate bigbluebutton_rails:install`, in migration I have table 
```
    create_table :bigbluebutton_server_configs do |t|
      t.integer :server_id
      t.text :available_layouts
      t.timestamps
    end
```
And now I can create server on PG database.

**Comment by daronco** [comment]
Whenever you update the gem, you should also consider that there might be new migrations that you have to add to your application. And usually there are. The wiki has information on how to migrate to an specific version of the gem, check [Migrate to 1.4.0](https://github.com/mconf/bigbluebutton_rails/wiki/Migrate-to-1.4.0).

You have to run commands such as the one below to create the migration file:

```bash
bundle exec rails generate bigbluebutton_rails:install 1.4.0 --migration-only
```
All migrations are in [this folder](https://github.com/mconf/bigbluebutton_rails/tree/master/lib/generators/bigbluebutton_rails/templates). You'll see that there is one for each version. Make sure you have them all (you might have only one migration including the content from them all, that's ok).

If you are running the latest version from master, you will not find a wiki page with instructions, so you'll have to copy the migration and check for other possible updates yourself.

Maybe the update process should be clearer in the README file, I'll review it.
