### ISSUE TITLE
Rails 4.2.0?

### ISSUE THREAD

**Issue by emclab** [mconf/bigbluebutton_rails#32]
This is probably not the place for questions. Is there a mailing list for asking questions?

It mentioned in manual that only Rails 4 supported. Is it including Rails 4.2.0? Is Ruby 2.2.3 OK as well? Thanks.

**Comment by daronco** [comment]
You can use Mconf's mailing list for questions: mconf-dev@googlegroups.com
I'll add this information to the README file.

We haven't tried it with Rails 4.2 yet, we're currently using it with [Rails 4.1 in Mconf-Web](https://github.com/mconf/mconf-web/blob/master/Gemfile#L4).
As for ruby 2.2.3, it should work. We've been using it with [ruby 2.2.0 in Mconf-Web](https://github.com/mconf/bigbluebutton_rails/blob/master/.ruby-version), so any patch version of 2.2 should be ok.
