### ISSUE TITLE
Rooms model's method select_server gives error on postgres

### ISSUE THREAD

**Issue by naumenko** [mconf/bigbluebutton_rails#4]
Just to let you know this method on postgres gives error
 
 # This method can be overridden to change the way the server is selected
  # before a room is created
  # This one selects the server with less rooms in it
  def select_server
    BigbluebuttonServer.
      select("bigbluebutton_servers.*, count(bigbluebutton_rooms.id) as room_count").
      joins(:rooms).group(:server_id).order("room_count ASC").first
  end

Error:
ActiveRecord::StatementInvalid (PG::Error: ERROR:  column "bigbluebutton_servers.id" must appear in the GROUP BY clause or be used in an aggregate function

**Comment by daronco** [comment]
Closing this because it's an old issue. If PostgreSQL is supported in the future, this will be solved.
