### ISSUE TITLE
Make the worker that waits for a meeting to start more reliable

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/bigbluebutton_rails#98]
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1065, http://dev.mconf.org/redmine/issues/1065

---

There's a resque worker that is triggered to start when a user starts or joins a conference, that will wait until the meeting is properly started in the webconference server to create a record in the database for this meeting. Currently it only tries to get information of a meeting once, ~15 seconds after the worker is started.  If the meeting takes longer that the time the worker waits before running, the worker won't find the meeting in the web conference server. 

It should try more that once to find the meeting (or simply trigger another worker if it fails, until it finds something, or until it decides that is time to stop).

**Comment by daronco** [comment]
Solved by PR #126.

The worker still just checks for a meeting start once, but now the process of creating meetings and ending them workers even if the workers are not running. After every `getMeetingInfo` call the meetings are created/updated, so the workers act only as a way to improve the speed in which updates are made.
